name: Script Still Working

on:
  push:
  schedule:
    - cron: '0 0 */2 * *' # Run every 2 days at midnight

jobs:
  update_dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Save Ethernet IP
      run: ip addr show | awk '/inet.*e(n.*s|th|o|np)/ {print $2}' | cut -d '/' -f 1 | tr -d '\n' > ethernet_ip.txt

    - name: Get Ethernet IP
      id: get_ip
      run: echo "IP=$(cat ethernet_ip.txt)" >> $GITHUB_ENV

    - name: Show Current Ethernet IP
      run: echo "Current Ethernet IP is $IP"

    - name: Update DNS record
      env:
        API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: python3 cf_ddns.py $API_TOKEN mip.my.id github-workflow-test 60 false $IP > output.txt
    
    - name: Display Last Line
      run: tail -n 1 output.txt
